# statically linking the C runtime on windows seems sensible?
[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]

[env]
# Use vendored OpenSSL to avoid system dependency issues on Linux CI
OPENSSL_STATIC = "1"